import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Local agent tooling: vendored skills and caches, not app source.
    ".claude/**",
    ".img2threejs/**",
    ".impeccable/**",
    ".atl/**",
    // Procedurally generated geometry, not hand-written.
    "src/lib/three/**",
    // Generated by Payload: schema migrations and the admin import map.
    "src/migrations/**",
    "src/payload-types.ts",
    "src/app/(payload)/admin/importMap.js",
  ]),
]);

export default eslintConfig;
